def NULL_not_found(object: any) -> int:
	try:
	
	
	except Exception as e:
		print("An error occured " + str(e))
